language: php
php:
  - '7.0'
env:
  global:
    - YY_TEST_SELENIUM_HOST="127.0.0.1"
    - YY_TEST_SELENIUM_PORT=4444
    - YY_TEST_BROWSER=firefox
    - YY_TEST_BASE_URL="http://127.0.0.1:8080"
install:
  - composer install --prefer-source --no-interaction
  - sudo build/setup.sh
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

