sudo: required
services:
  - docker
language: none
env:
  global:
    - USER=travis
    - UID=1000
  matrix:
#    - YY_TEST_SELENIUM_HOST=127.0.0.1 YY_TEST_BROWSER=firefox
    - YY_TEST_SELENIUM_HOST=hub YY_TEST_BROWSER=chrome
    - YY_TEST_SELENIUM_HOST=hub YY_TEST_BROWSER=firefox
before_install:
- mkdir -p default/runtime/log && chmod a+rwX -R default/runtime
- cd docker && docker-compose up -d
- sleep 20
- docker-compose ps
- docker-compose logs php
- docker-compose exec -T php sh -c "curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer"
- docker-compose exec -T php composer update
script:
#- docker-compose exec -T web curl -i http://web
#- docker-compose exec -T tests curl -i http://web
- docker-compose exec -T php vendor/bin/phpunit
