version: "2.1"
services:
  hub:
    image: selenium/hub
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ""
    expose:
      - "4444"
  php:
    image: bitnami/php-fpm:latest
    hostname: php
    environment:
      YY_TEST_BROWSER: "$YY_TEST_BROWSER"
      YY_TEST_BASE_URL: http://web
      YY_TEST_SELENIUM_HOST: hub
      YY_TEST_SELENIUM_PORT: 4444
    links:
      - hub
    expose:
      - "9000"
    volumes:
      - ./..:/app
  web:
    image: bitnami/nginx:latest
    hostname: web
    links:
      - php
    expose:
      - "80"
      - "443"
    volumes:
      - ./yy.nginx.conf:/bitnami/nginx/conf/vhosts/yy.conf
      - ./..:/app
  node:
    image: "selenium/node-$YY_TEST_BROWSER"
    links:
      - web
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
    entrypoint: ["/bin/sh", "-c", "sleep 3; /opt/bin/entry_point.sh"]
