version: "3"
services:
  php:
    image: bitnami/php-fpm:latest
    hostname: php
    expose:
      - "9000"
    volumes:
      - ./..:/app
  web:
    image: bitnami/nginx:latest
    hostname: web
    links:
      - php
    expose:
      - "80"
      - "443"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./yy.nginx.conf:/bitnami/nginx/conf/vhosts/yy.conf
      - ./..:/app
